'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  bn: {
    languageLabel: 'ভাষা সেটিংস',
    languageHelper: 'বাংলা বা ইংরেজি নির্বাচন করুন।',
    languageToggleLabel: 'ভাষা নির্বাচন',
    english: 'English',
    bangla: 'বাংলা',
    saveNote: 'পরিবর্তন সাথে সাথে কার্যকর হবে।',
    guestBadge: '🩺 MatriSense · মাতৃত্বকালীন ঝুঁকি মূল্যায়ন',
    guestTitle: 'নিরাপদ মাতৃত্বের জন্য এক ধাপে এক ধাপে সহায়তা',
    guestSubtitle:
      'MatriSense হলো বাংলা-প্রথম মাতৃত্বকালীন স্বাস্থ্য ট্রায়াজ সিস্টেম। এটি কোনো রোগ নির্ণয় বা চিকিৎসা নির্দেশনা দেয় না—ঝুঁকি বুঝতে এবং সঠিক পদক্ষেপ নিতে সহায়তা করে।',
    login: 'লগইন করুন',
    register: 'অ্যাকাউন্ট তৈরি করুন',
    roleHint: 'ভূমিকা নির্বাচন করুন: মা (Mother) অথবা স্বাস্থ্যকর্মী (Health Worker)',
    stepsTitle: 'ট্রায়াজ ধাপগুলো',
    stepsProgress: 'Step 1/6',
    steps: [
      {
        title: 'মা-এর প্রোফাইল পূরণ করুন',
        text: 'নাম, বয়স, গর্ভকাল ও জরুরি যোগাযোগ যুক্ত করুন।',
      },
      {
        title: 'উপসর্গ লিখুন (বাংলা)',
        text: 'আপনার অনুভূত লক্ষণগুলো সহজ বাংলায় লিখুন।',
      },
      {
        title: 'AI দ্বারা যাচাই',
        text: 'AI আপনার উপসর্গগুলো শনাক্ত করবে—আপনি নিশ্চিত করবেন।',
      },
      {
        title: 'ফলো-আপ প্রশ্ন',
        text: '২-৩টি সংক্ষিপ্ত প্রশ্নের উত্তর দিন।',
      },
      {
        title: 'ঝুঁকি ফলাফল',
        text: 'LOW / MEDIUM / HIGH ঝুঁকি কার্ড দেখাবে।',
      },
      {
        title: 'করণীয় নির্দেশনা',
        text: 'এখন কী করবেন, কী পর্যবেক্ষণ করবেন, সতর্ক সংকেত।',
      },
    ],
    low: 'কম ঝুঁকি',
    medium: 'মাঝারি ঝুঁকি',
    high: 'উচ্চ ঝুঁকি',
    lowHelp: 'স্বাভাবিক পর্যবেক্ষণ চালিয়ে যান।',
    mediumHelp: 'স্বাস্থ্যকর্মীর সাথে দ্রুত যোগাযোগ করুন।',
    highHelp: 'জরুরি সেবায় যান অথবা কল করুন।',
    disclaimerTitle: 'সতর্ক বার্তা',
    disclaimerBody:
      'MatriSense রোগ নির্ণয় করে না এবং ওষুধ সেবনের পরামর্শ দেয় না। উপসর্গ গুরুতর হলে দ্রুত নিকটস্থ চিকিৎসা কেন্দ্রে যোগাযোগ করুন।',
    patientWelcome: 'স্বাগতম',
    patientLead: 'আজকের অনুভূতি জানান, আমরা ঝুঁকি নির্ধারণ করে করণীয় জানাবো।',
    patientStart: 'নতুন ট্রায়াজ শুরু করুন',
    patientHistory: 'পূর্বের ইতিহাস দেখুন',
    goToDashboard: 'ড্যাশবোর্ডে যান',
    patientStatus: 'আজকের অবস্থা',
    patientNext: 'পরবর্তী পদক্ষেপ',
    patientNextValue: 'উপসর্গ লিখুন',
    patientNextHelp: 'বাংলায় আপনার লক্ষণ জানান।',
    patientSupport: 'সহায়তা',
    patientSupportHelp: 'প্রয়োজনে দ্রুত যোগাযোগ করুন।',
    patientWarningTitle: 'সতর্ক সংকেত',
    patientWarningBody: 'মাথা ঘোরা, তীব্র ব্যথা বা রক্তপাত হলে দ্রুত চিকিৎসা কেন্দ্রে যান। MatriSense রোগ নির্ণয় করে না।',
    quickActions: 'দ্রুত পদক্ষেপ',
    reportSymptoms: 'উপসর্গ জানান',
    reportSymptomsHelp: 'বাংলায় আপনার লক্ষণ লিখুন।',
    viewHistory: 'ইতিহাস দেখুন',
    viewHistoryHelp: 'পূর্বের ট্রায়াজ ফলাফল দেখুন।',
    myProfile: 'আমার প্রোফাইল',
    myProfileHelp: 'গর্ভকাল ও যোগাযোগ আপডেট করুন।',
    emergencyHelp: 'জরুরি সহায়তা',
    emergencyHelpText: 'দ্রুত স্বাস্থ্যকর্মীর সাথে যোগাযোগ করুন।',
    yourSummary: 'আপনার সারাংশ',
    active: 'সক্রিয়',
    triageSessions: 'ট্রায়াজ সেশন',
    nextCheckup: 'পরবর্তী চেকআপের তারিখ',
    currentRisk: 'বর্তমান ঝুঁকি স্তর',
    healthWorkerReferrals: 'স্বাস্থ্যকর্মী রেফারেল',
    healthWorkerReferralsHelp: 'আপনার স্বাস্থ্যকর্মীর পাঠানো হাসপাতাল রেফারেল দেখুন',
    loadingReferrals: 'রেফারেল লোড হচ্ছে...',
    referralsFromWorker: 'আপনার নির্ধারিত স্বাস্থ্যকর্মীর পাঠানো রেফারেলসমূহ',
    back: 'ফিরে যান',
    newReferralsCount: 'আপনার নতুন রেফারেল রয়েছে',
    noReferralsYet: 'এখনো কোনো রেফারেল নেই',
    noReferralsYetHelp: 'আপনার স্বাস্থ্যকর্মী রেফারেল পাঠালে তা এখানে প্রদর্শিত হবে',
    hospitalAssignment: 'হাসপাতাল অ্যাসাইনমেন্ট',
    pending: 'অপেক্ষমান',
    acknowledged: 'গৃহীত',
    type: 'ধরন',
    address: 'ঠিকানা',
    phone: 'ফোন',
    services: 'সেবাসমূহ',
    reasonForReferral: 'রেফারেলের কারণ:',
    sent: 'পাঠানো হয়েছে:',
    markAsRead: '✓ পঠিত হিসেবে চিহ্নিত করুন',
    acknowledge: '✓ গ্রহণ নিশ্চিত করুন',
    callHospital: '📞 হাসপাতালে কল করুন',
    autoRefreshing: '🔄 প্রতি ১০ সেকেন্ড পর পর স্বয়ংক্রিয়ভাবে রিফ্রেশ হচ্ছে',
    workerTitle: 'ড্যাশবোর্ড (ডেমো)',
    workerSubtitle: 'এটি একটি ডেমো ড্যাশবোর্ড—শিগগিরই লাইভ কেস যুক্ত হবে।',
    workerStats: ['নতুন কেস', 'উচ্চ ঝুঁকি', 'মাঝারি ঝুঁকি', 'লো ঝুঁকি'],
    workerCasesTitle: 'সাম্প্রতিক কেস (ডেমো)',
    workerTag: 'মাঝারি',
    adminTitle: 'সিস্টেম ওভারভিউ',
    adminSubtitle: 'এখানে প্ল্যাটফর্ম স্বাস্থ্য ও রেফারেল সারাংশ দেখানো হবে।',
    adminUsers: 'মোট ব্যবহারকারী',
    adminCases: 'সক্রিয় কেস',
    adminReferrals: 'রেফারেল',
    adminNotes: 'সিস্টেম নোট',
    adminNoteItems: [
      'রোল ভিত্তিক অ্যাক্সেস সক্রিয়।',
      'ঝুঁকি স্তর ও কেস রেফারেল নিয়ম এখানে আসবে।',
      'ডেটা সোর্স যোগ হলে অ্যানালিটিক্স দেখানো হবে।',
    ],
    profile: {
      title: '👤 আমার প্রোফাইল',
      subtitle: 'আপনার ব্যক্তিগত তথ্য, গর্ভাবস্থার বিবরণ এবং ঐচ্ছিক নথিপত্র পরিচালনা করুন।',
      basicInfo: 'প্রাথমিক তথ্য',
      name: 'নাম',
      age: 'বয়স',
      phone: 'মোবাইল নম্বর',
      email: 'ইমেইল (ঐচ্ছিক)',
      pregnancyDetails: 'গর্ভাবস্থার বিবরণ',
      trimester: 'বর্তমান ত্রৈমাসিক (গর্ভকাল)',
      firstTrimester: 'প্রথম ত্রৈমাসিক (০-১৩ সপ্তাহ)',
      secondTrimester: 'দ্বিতীয় ত্রৈমাসিক (১৪-২৬ সপ্তাহ)',
      thirdTrimester: 'তৃতীয় ত্রৈমাসিক (২৭+ সপ্তাহ)',
      unknown: 'অজানা',
      gestationalWeek: 'গর্ভাবস্থার সপ্তাহ (ঐচ্ছিক)',
      expectedDeliveryDate: 'সম্ভাব্য প্রসবের তারিখ (ঐচ্ছিক)',
      lastCheckupDate: 'শেষ চেকআপের তারিখ (ঐচ্ছিক)',
      locationRegion: 'অবস্থান ও অঞ্চল',
      locationHelper: 'স্বাস্থ্যকর্মীদের দ্রুত রেফারেল সমন্বয়ে সাহায্য করে।',
      division: 'বিভাগ',
      district: 'জেলা',
      upazila: 'উপজেলা / থানা',
      village: 'ঠিকানা / গ্রাম',
      emergencyContact: 'জরুরি যোগাযোগ',
      contactName: 'যোগাযোগের নাম',
      contactPhone: 'যোগাযোগের মোবাইল নম্বর',
      identification: 'শনাক্তকরণ তথ্য (ঐচ্ছিক)',
      idHelper: 'এই তথ্যগুলো সম্পূর্ণ ঐচ্ছিক এবং স্থানীয় স্বাস্থ্যকেন্দ্রগুলোকে রেকর্ড বজায় রাখতে সাহায্য করে।',
      nationalId: 'জাতীয় পরিচয়পত্র (NID)',
      birthCertificate: 'জন্ম নিবন্ধন নম্বর',
      privacyConsent: 'গোপনীয়তা ও সম্মতি',
      consentShare: 'স্থানীয় স্বাস্থ্যকর্মীদের আমার ট্রায়াজ ইতিহাস দেখার অনুমতি দিন (পরামর্শিত)',
      consentLocation: 'রেফারেলের জন্য কাছাকাছি হাসপাতাল সাজেস্ট করতে আমার অবস্থান ডেটা ব্যবহার করুন',
      consentStore: 'মেডিকেল কাগজপত্র ও আইডি নিরাপদে সংরক্ষণের সম্মতি দিন',
      saveButton: 'প্রোফাইল সেভ করুন',
      savingButton: 'সেভ হচ্ছে...',
      documentsTitle: 'মেডিকেল নথিপত্র ও প্রশংসাপত্র (ঐচ্ছিক)',
      documentsHelper: 'বিঃদ্রঃ: নথিপত্র প্রদান ১০০% ঐচ্ছিক। MatriSense AI ট্রায়াজ কোনো নথি ছাড়াই কাজ করে। পুরোনো রিপোর্ট আপলোড করলে রেফারেলের সময় স্বাস্থ্যকর্মীদের সুবিধা হয়।',
      docType: 'নথিপত্রের ধরন',
      docTitle: 'পছন্দনীয় শিরোনাম (ঐচ্ছিক)',
      docTitlePlaceholder: 'যেমনঃ ১০ সেপ্টেম্বরের স্ক্যান',
      selectFile: 'ফাইল নির্বাচন করুন (সর্বোচ্চ ৫ MB)',
      uploadButton: '📤 নথি আপলোড করুন',
      uploadingButton: 'আপলোড হচ্ছে...',
      uploadedDocsList: 'আপলোডকৃত নথিপত্র',
      noDocs: 'এখনো কোনো নথি আপলোড করা হয়নি।',
      viewDoc: 'দেখুন',
      deleteDoc: 'মুছে ফেলুন',
      dangerZone: 'বিপজ্জনক জোন',
      dangerHelper: 'অ্যাকাউন্ট নিষ্ক্রিয় করলে আপনি প্ল্যাটফর্মে অ্যাক্সেস হারাবেন। ড্যাশবোর্ড থেকে এই অ্যাকশন বাতিল করা যাবে না।',
      deactivateButton: 'অ্যাকাউন্ট নিষ্ক্রিয় করুন',
      confirmDeleteDoc: 'আপনি কি নিশ্চিত যে এই নথিটি মুছতে চান?',
      confirmDeactivate: 'আপনি কি নিশ্চিত? অ্যাকাউন্ট নিষ্ক্রিয় করলে অবিলম্বে লগ আউট হয়ে যাবেন এবং এটি পূর্বাবস্থায় ফিরিয়ে আনা যাবে না।',
      deactivateSuccess: 'আপনার অ্যাকাউন্ট সফলভাবে নিষ্ক্রিয় করা হয়েছে।',
      deactivateFail: 'অ্যাকাউন্ট নিষ্ক্রিয় করতে ব্যর্থ: ',
      createError: 'নাম, বয়স এবং ত্রৈমাসিক তথ্য আবশ্যক।',
      createSuccess: 'প্রোফাইল সফলভাবে তৈরি হয়েছে।',
      createFail: 'প্রোফাইল তৈরি করতে ব্যর্থ: ',
      updateSuccess: 'প্রোফাইল সফলভাবে আপডেট হয়েছে।',
      updateFail: 'প্রোফাইল আপডেট করতে ব্যর্থ: ',
      errorSaving: 'সেভ করার সময় ত্রুটি হয়েছে।',
      docTypes: {
        NATIONAL_ID: 'জাতীয় পরিচয়পত্র (NID)',
        BIRTH_CERTIFICATE: 'জন্ম নিবন্ধন',
        PREVIOUS_MEDICAL_REPORT: 'পূর্বের মেডিকেল রিপোর্ট',
        PRESCRIPTION: 'প্রেসক্রিপশন',
        ULTRASOUND_REPORT: 'আল্ট্রাসাউন্ড রিপোর্ট',
        LAB_REPORT: 'ল্যাব রিপোর্ট',
        OTHER_MEDICAL_DOCUMENT: 'অন্যান্য নথি'
      }
    }
  },
  en: {
    languageLabel: 'Language settings',
    languageHelper: 'Choose Bengali or English.',
    languageToggleLabel: 'Language',
    english: 'English',
    bangla: 'বাংলা',
    saveNote: 'Changes apply instantly.',
    guestBadge: '🩺 MatriSense · Maternal health triage',
    guestTitle: 'Step-by-step guidance for safer motherhood',
    guestSubtitle:
      'MatriSense is a Bangla-first maternal health triage system. It does not diagnose disease or prescribe medicine— it helps you understand risk and next steps.',
    login: 'Log in',
    register: 'Create account',
    roleHint: 'Choose a role: Mother or Health Worker',
    stepsTitle: 'Triage steps',
    stepsProgress: 'Step 1/6',
    steps: [
      {
        title: 'Complete mother profile',
        text: 'Add name, age, gestational weeks, and emergency contact.',
      },
      {
        title: 'Describe symptoms (Bangla)',
        text: 'Write your symptoms in simple Bangla text.',
      },
      {
        title: 'AI confirmation',
        text: 'AI extracts symptoms— you confirm them.',
      },
      {
        title: 'Follow-up questions',
        text: 'Answer 2–3 short questions.',
      },
      {
        title: 'Risk result',
        text: 'LOW / MEDIUM / HIGH risk card is shown.',
      },
      {
        title: 'Care guidance',
        text: 'What to do now, what to monitor, warning signs.',
      },
    ],
    low: 'Low risk',
    medium: 'Medium risk',
    high: 'High risk',
    lowHelp: 'Continue regular monitoring.',
    mediumHelp: 'Contact a health worker soon.',
    highHelp: 'Seek urgent care or call for help.',
    disclaimerTitle: 'Safety notice',
    disclaimerBody:
      'MatriSense does not diagnose disease or prescribe medicine. If symptoms are severe, contact a nearby clinic immediately.',
    patientWelcome: 'Welcome back',
    patientLead: 'Share how you feel today and we will guide next steps.',
    patientStart: 'Start new triage',
    patientHistory: 'View history',
    goToDashboard: 'Go to dashboard',
    patientStatus: 'Today’s status',
    patientNext: 'Next step',
    patientNextValue: 'Describe symptoms',
    patientNextHelp: 'Write your symptoms in Bangla.',
    patientSupport: 'Support',
    patientSupportHelp: 'Reach a health worker when needed.',
    patientWarningTitle: 'Warning signs',
    patientWarningBody: 'If you feel dizzy, severe pain, or bleeding, seek care immediately. MatriSense does not diagnose.',
    quickActions: 'Quick actions',
    reportSymptoms: 'Report symptoms',
    reportSymptomsHelp: 'Describe how you feel in Bangla.',
    viewHistory: 'View history',
    viewHistoryHelp: 'See past triage results.',
    myProfile: 'My profile',
    myProfileHelp: 'Update pregnancy details and contacts.',
    emergencyHelp: 'Emergency help',
    emergencyHelpText: 'Reach a health worker immediately.',
    yourSummary: 'Your summary',
    active: 'Active',
    triageSessions: 'Triage sessions',
    nextCheckup: 'Next checkup date',
    currentRisk: 'Current risk level',
    healthWorkerReferrals: 'Health Worker Referrals',
    healthWorkerReferralsHelp: 'View hospital referrals from your health worker',
    loadingReferrals: 'Loading referrals...',
    referralsFromWorker: 'Referrals from your assigned health worker',
    back: 'Back',
    newReferralsCount: 'You have new referrals',
    noReferralsYet: 'No referrals yet',
    noReferralsYetHelp: 'Your referrals will appear here once your health worker sends them',
    hospitalAssignment: 'Hospital Assignment',
    pending: 'PENDING',
    acknowledged: 'ACKNOWLEDGED',
    type: 'Type',
    address: 'Address',
    phone: 'Phone',
    services: 'Services',
    reasonForReferral: 'Reason for Referral:',
    sent: 'Sent:',
    markAsRead: '✓ Mark as Read',
    acknowledge: '✓ Acknowledge',
    callHospital: '📞 Call Hospital',
    autoRefreshing: '🔄 Auto-refreshing every 10 seconds',
    workerTitle: 'Dashboard (demo)',
    workerSubtitle: 'This is a demo dashboard—live cases will appear soon.',
    workerStats: ['New cases', 'High risk', 'Medium risk', 'Low risk'],
    workerCasesTitle: 'Recent cases (demo)',
    workerTag: 'Medium',
    adminTitle: 'System overview',
    adminSubtitle: 'Platform health and referral summary will appear here.',
    adminUsers: 'Total users',
    adminCases: 'Active cases',
    adminReferrals: 'Referrals',
    adminNotes: 'System notes',
    adminNoteItems: [
      'Role-based access is active.',
      'Risk and referral rules will be shown here.',
      'Analytics will appear when data sources are connected.',
    ],
    profile: {
      title: '👤 My Profile',
      subtitle: 'Manage your personal information, pregnancy details, and optional documents.',
      basicInfo: 'Basic Information',
      name: 'Name',
      age: 'Age',
      phone: 'Phone Number',
      email: 'Email (Optional)',
      pregnancyDetails: 'Pregnancy Details',
      trimester: 'Current Trimester',
      firstTrimester: 'First Trimester (0-13 weeks)',
      secondTrimester: 'Second Trimester (14-26 weeks)',
      thirdTrimester: 'Third Trimester (27+ weeks)',
      unknown: 'Unknown',
      gestationalWeek: 'Gestational Week (Optional)',
      expectedDeliveryDate: 'Expected Delivery Date (EDD) (Optional)',
      lastCheckupDate: 'Last Checkup Date (Optional)',
      locationRegion: 'Location & Region',
      locationHelper: 'Helping health workers coordinate referrals quickly.',
      division: 'Division',
      district: 'District',
      upazila: 'Upazila / Thana',
      village: 'Address / Village',
      emergencyContact: 'Emergency Contact',
      contactName: 'Contact Name',
      contactPhone: 'Contact Phone',
      identification: 'Identification (Optional)',
      idHelper: 'These fields are entirely optional and help local health facilities organize records.',
      nationalId: 'National ID (NID)',
      birthCertificate: 'Birth Certificate Number',
      privacyConsent: 'Privacy & Consent',
      consentShare: 'Allow local health workers to view my triage history (recommended)',
      consentLocation: 'Use my location data to suggest nearby hospitals for referrals',
      consentStore: 'Consent to securely store medical documents and IDs',
      saveButton: 'Save Profile Details',
      savingButton: 'Saving...',
      documentsTitle: 'Medical Documents & Certifications (Optional)',
      documentsHelper: 'Note: Documents are 100% optional. The MatriSense AI triage works perfectly without them. Uploading previous reports helps health workers assist you during medical referrals.',
      docType: 'Document Type',
      docTitle: 'Custom Title (Optional)',
      docTitlePlaceholder: 'e.g., Scan from Sept 10',
      selectFile: 'Select File (Max 5MB)',
      uploadButton: '📤 Upload Document',
      uploadingButton: 'Uploading...',
      uploadedDocsList: 'Uploaded Documents',
      noDocs: 'No documents uploaded yet.',
      viewDoc: 'View',
      deleteDoc: 'Delete',
      dangerZone: 'Danger Zone',
      dangerHelper: 'Once you deactivate your account, you will lose access to the platform and your active triage sessions. This action is permanent and cannot be undone directly from the dashboard.',
      deactivateButton: 'Deactivate Account',
      confirmDeleteDoc: 'Are you sure you want to delete this document?',
      confirmDeactivate: 'Are you sure you want to deactivate your account? This action cannot be undone. You will be logged out immediately.',
      deactivateSuccess: 'Your account has been successfully deactivated.',
      deactivateFail: 'Failed to deactivate account: ',
      createError: 'Name, age and trimester are required to create a profile.',
      createSuccess: 'Profile created successfully.',
      createFail: 'Failed to create profile: ',
      updateSuccess: 'Profile updated successfully.',
      updateFail: 'Failed to update profile: ',
      errorSaving: 'An error occurred while saving.',
      docTypes: {
        NATIONAL_ID: 'National ID',
        BIRTH_CERTIFICATE: 'Birth Certificate',
        PREVIOUS_MEDICAL_REPORT: 'Previous Medical Report',
        PRESCRIPTION: 'Prescription',
        ULTRASOUND_REPORT: 'Ultrasound Report',
        LAB_REPORT: 'Lab Report',
        OTHER_MEDICAL_DOCUMENT: 'Other Document'
      }
    }
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('bn');

  useEffect(() => {
    const saved = localStorage.getItem('matrisense_lang');
    if (saved === 'bn' || saved === 'en') {
      setLanguage(saved);
    }
  }, []);

  const updateLanguage = (next) => {
    setLanguage(next);
    localStorage.setItem('matrisense_lang', next);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage: updateLanguage,
      t: translations[language],
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
