-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.active_geofences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL,
  itinerary_id uuid NOT NULL,
  place_id character varying NOT NULL,
  place_name character varying NOT NULL,
  latitude double precision NOT NULL CHECK (latitude >= '-90'::integer::double precision AND latitude <= 90::double precision),
  longitude double precision NOT NULL CHECK (longitude >= '-180'::integer::double precision AND longitude <= 180::double precision),
  radius integer NOT NULL,
  status character varying NOT NULL DEFAULT 'active'::character varying,
  place_category character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT active_geofences_pkey PRIMARY KEY (id),
  CONSTRAINT active_geofences_itinerary_id_fkey FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id)
);
CREATE TABLE public.chat_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL,
  message text NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['user'::character varying, 'ai'::character varying]::text[])),
  session_id character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  short_description text,
  google_place_id character varying UNIQUE,
  latitude numeric CHECK (latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  country_id uuid NOT NULL,
  country_name character varying,
  state_province character varying,
  population bigint,
  area numeric,
  best_time_to_visit character varying,
  average_temperature character varying,
  famous_for ARRAY,
  poi_breakdown jsonb DEFAULT '{"urban": 0, "nature": 0, "history": 0}'::jsonb,
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_visitors integer DEFAULT 0,
  popularity_score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location USER-DEFINED,
  CONSTRAINT cities_pkey PRIMARY KEY (id),
  CONSTRAINT cities_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.conversation_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  user_id character varying NOT NULL,
  joined_at timestamp with time zone DEFAULT now(),
  last_read_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversation_participants_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_participants_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['group'::character varying, 'dm'::character varying]::text[])),
  context_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.countries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  slug character varying NOT NULL UNIQUE,
  description text,
  short_description text,
  google_place_id character varying UNIQUE,
  latitude numeric CHECK (latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  country_code character NOT NULL UNIQUE,
  continent character varying NOT NULL,
  capital character varying,
  currency character,
  languages ARRAY,
  population bigint,
  area numeric,
  visa_required boolean DEFAULT false,
  best_time_to_visit character varying,
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_visitors integer DEFAULT 0,
  popularity_score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location USER-DEFINED,
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.geofence_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL,
  geofence_radius integer DEFAULT 100,
  auto_checkin boolean DEFAULT true,
  auto_checkout boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT geofence_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.group_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_trip_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  assigned_to character varying,
  created_by character varying NOT NULL,
  status character varying DEFAULT 'todo'::character varying,
  priority character varying DEFAULT 'medium'::character varying,
  due_date date,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_activities_pkey PRIMARY KEY (id),
  CONSTRAINT group_activities_group_trip_id_fkey FOREIGN KEY (group_trip_id) REFERENCES public.group_trips(id)
);
CREATE TABLE public.group_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_trip_id uuid NOT NULL,
  paid_by character varying NOT NULL,
  title character varying NOT NULL,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'BDT'::character varying,
  category character varying DEFAULT 'other'::character varying,
  split_type character varying DEFAULT 'equal'::character varying,
  split_among jsonb DEFAULT '[]'::jsonb,
  custom_splits jsonb DEFAULT '{}'::jsonb,
  receipt_url text,
  notes text,
  expense_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT group_expenses_group_trip_id_fkey FOREIGN KEY (group_trip_id) REFERENCES public.group_trips(id)
);
CREATE TABLE public.group_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_trip_id uuid NOT NULL,
  user_id character varying NOT NULL,
  role character varying DEFAULT 'member'::character varying,
  status character varying DEFAULT 'pending'::character varying,
  joined_via character varying DEFAULT 'discovery'::character varying,
  joined_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  party_size integer DEFAULT 1,
  CONSTRAINT group_members_pkey PRIMARY KEY (id),
  CONSTRAINT group_members_group_trip_id_fkey FOREIGN KEY (group_trip_id) REFERENCES public.group_trips(id)
);
CREATE TABLE public.group_trips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organizer_id character varying NOT NULL,
  itinerary_id uuid,
  title character varying NOT NULL,
  description text,
  cover_image text,
  destination_tags jsonb DEFAULT '[]'::jsonb,
  date_range_start date,
  date_range_end date,
  activity_type character varying,
  max_participants integer DEFAULT 10,
  cost_per_person numeric DEFAULT 0,
  currency character varying DEFAULT 'BDT'::character varying,
  is_public boolean DEFAULT true,
  auto_approve boolean DEFAULT false,
  invite_code character varying NOT NULL UNIQUE,
  status character varying DEFAULT 'open'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT group_trips_pkey PRIMARY KEY (id),
  CONSTRAINT group_trips_itinerary_id_fkey FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id)
);
CREATE TABLE public.itineraries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL,
  trip_name character varying NOT NULL,
  selected_places jsonb,
  selected_itinerary jsonb,
  status character varying DEFAULT 'draft'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  trip_status character varying DEFAULT 'planning'::character varying,
  map_routes jsonb,
  transport_mode character varying DEFAULT 'walking'::character varying,
  creation_method character varying DEFAULT 'ai'::character varying,
  trip_start_date timestamp with time zone,
  trip_end_date timestamp with time zone,
  actual_start_time timestamp with time zone,
  actual_end_time timestamp with time zone,
  budget_total numeric,
  amount_spent numeric DEFAULT 0,
  CONSTRAINT itineraries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  sender_id character varying NOT NULL,
  sender_username character varying,
  content text NOT NULL,
  message_type character varying NOT NULL DEFAULT 'text'::character varying CHECK (message_type::text = ANY (ARRAY['text'::character varying, 'system'::character varying, 'join'::character varying, 'leave'::character varying]::text[])),
  mentions jsonb DEFAULT '[]'::jsonb,
  is_deleted boolean DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.nearby_pois (
  poi_id uuid NOT NULL,
  nearby_poi_id uuid NOT NULL,
  distance_km numeric NOT NULL CHECK (distance_km > 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nearby_pois_pkey PRIMARY KEY (poi_id, nearby_poi_id),
  CONSTRAINT nearby_pois_poi_id_fkey FOREIGN KEY (poi_id) REFERENCES public.pois(id),
  CONSTRAINT nearby_pois_nearby_poi_id_fkey FOREIGN KEY (nearby_poi_id) REFERENCES public.pois(id)
);
CREATE TABLE public.notification_preferences (
  user_id character varying NOT NULL,
  arrival_notifications boolean DEFAULT true,
  departure_notifications boolean DEFAULT true,
  time_warning_notifications boolean DEFAULT true,
  off_route_notifications boolean DEFAULT true,
  next_place_notifications boolean DEFAULT true,
  quiet_hours_enabled boolean DEFAULT false,
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  notification_frequency character varying DEFAULT 'normal'::character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id)
);
CREATE TABLE public.place_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  url character varying NOT NULL,
  caption text,
  alt_text text,
  display_order integer DEFAULT 0,
  place_id uuid NOT NULL,
  place_type USER-DEFINED NOT NULL,
  uploaded_by uuid,
  is_verified boolean DEFAULT false,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT place_images_pkey PRIMARY KEY (id)
);
CREATE TABLE public.place_search_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  search_query character varying NOT NULL,
  place_data jsonb NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp without time zone,
  CONSTRAINT place_search_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.places (
  place_id integer NOT NULL DEFAULT nextval('places_place_id_seq'::regclass),
  name text NOT NULL,
  primary_category text,
  tags ARRAY,
  short_desc text,
  visit_duration_min integer,
  est_cost_per_day numeric,
  source text,
  verified boolean DEFAULT false,
  country text,
  region text,
  location USER-DEFINED,
  created_at timestamp without time zone DEFAULT now(),
  google_place_id character varying UNIQUE,
  city character varying,
  city_id uuid,
  country_id uuid,
  neighborhood character varying,
  address text,
  opening_hours jsonb,
  entry_fee jsonb,
  accessibility jsonb,
  website character varying,
  phone_number character varying,
  email character varying,
  amenities ARRAY,
  macro_category character varying CHECK (macro_category::text = ANY (ARRAY['Urban'::character varying, 'Nature'::character varying, 'History'::character varying]::text[])),
  average_rating numeric DEFAULT 0,
  total_reviews integer DEFAULT 0,
  popularity_score integer DEFAULT 0,
  secondary_category character varying,
  CONSTRAINT places_pkey PRIMARY KEY (place_id),
  CONSTRAINT places_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT places_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.pois (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL,
  description text,
  short_description text,
  google_place_id character varying UNIQUE,
  latitude numeric CHECK (latitude >= '-90'::integer::numeric AND latitude <= 90::numeric),
  longitude numeric CHECK (longitude >= '-180'::integer::numeric AND longitude <= 180::numeric),
  city_id uuid NOT NULL,
  city_name character varying,
  country_id uuid NOT NULL,
  country_name character varying,
  category USER-DEFINED NOT NULL,
  sub_category USER-DEFINED,
  tags ARRAY,
  address text,
  neighborhood character varying,
  opening_hours jsonb,
  entry_fee jsonb,
  estimated_duration character varying,
  accessibility jsonb,
  website character varying,
  phone_number character varying,
  email character varying,
  amenities ARRAY,
  features ARRAY,
  best_time_of_day character varying,
  best_season character varying,
  crowd_level character varying,
  total_reviews integer DEFAULT 0,
  average_rating numeric DEFAULT 0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_visitors integer DEFAULT 0,
  popularity_score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  location USER-DEFINED,
  CONSTRAINT pois_pkey PRIMARY KEY (id),
  CONSTRAINT pois_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT pois_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.review_images (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  review_id uuid NOT NULL,
  url character varying NOT NULL,
  caption text,
  display_order integer DEFAULT 0,
  uploaded_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT review_images_pkey PRIMARY KEY (id),
  CONSTRAINT review_images_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  place_id uuid NOT NULL,
  place_type USER-DEFINED NOT NULL,
  place_name character varying,
  user_id uuid NOT NULL,
  user_name character varying,
  user_avatar character varying,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text,
  visit_date date,
  images jsonb DEFAULT '[]'::jsonb,
  helpful_count integer DEFAULT 0 CHECK (helpful_count >= 0),
  is_verified boolean DEFAULT false,
  was_edited boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id)
);
CREATE TABLE public.top_places (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  parent_id uuid NOT NULL,
  parent_type USER-DEFINED NOT NULL CHECK (parent_type = ANY (ARRAY['COUNTRY'::place_type, 'CITY'::place_type])),
  poi_id uuid NOT NULL,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT top_places_pkey PRIMARY KEY (id),
  CONSTRAINT top_places_poi_id_fkey FOREIGN KEY (poi_id) REFERENCES public.pois(id)
);
CREATE TABLE public.visit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id character varying NOT NULL,
  itinerary_id uuid NOT NULL,
  place_id character varying NOT NULL,
  place_name character varying NOT NULL,
  entered_at timestamp without time zone NOT NULL DEFAULT now(),
  exited_at timestamp without time zone,
  time_spent integer,
  expected_duration integer,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'skipped'::character varying]::text[])),
  entry_location jsonb,
  exit_location jsonb,
  user_rating integer CHECK (user_rating >= 1 AND user_rating <= 5),
  notes text,
  photos jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT visit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT visit_logs_itinerary_id_fkey FOREIGN KEY (itinerary_id) REFERENCES public.itineraries(id)
);